Revert "unqlite: fix warning"
This reverts commit da8b76fc9a046bcb3e0a16f74e63bdc0017aedce.

Reason for revert:

new warning caused

 unqlite/unqlite.c:27068:52: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
14:54:53  27068 |                 if( zSrc >= zEnd ){break;} zSrc[0] = 0; zSrc++;
14:54:53        |                                            ~~~~~~~~^~~
14:54:53  unqlite/unqlite.c: In function 'MemHashInit':
14:54:53  unqlite/unqlite.c:51830:22: note: at offset 68 into destination object 'sAlloc' of size 68
14:54:53  51830 |         SyMemBackend sAlloc;